default: &default
  adapter: postgresql
  encoding: unicode
  username: quacker_user
  password: quacker


  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: simple_twitter_development


test:
  <<: *default
  database: simple_twitter_test

production:
  <<: *default
  database: simple_twitter_production


