# Define the default configuration
default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  pool: 5
  username: admin
  password: "admin"

# Development environment
development:
  <<: *default
  database: simple_twitter_development

# Test environment
test:
  <<: *default
  database: simple_twitter_test

# Production environment
production:
  <<: *default
  database: simple_twitter_production

